#!/bin/bash
# Optional cleanup commands
echo "Removing your application."

# Remove the application binary
rm -f /usr/bin/linux-mint-panel-customizer
rm -f /usr/bin/modify_cinnamon_css.sh

# Remove the application library
rm -rf /usr/lib/linux-mint-panel-customizer

# Remove the application icons and desktop files
rm -rf /usr/share/icons/panel-customizer.png
rm -rf /usr/share/applications/linux-mint-panel-customizer.desktop

echo "Your application has been removed."